### ISSUE TITLE
PyMuPDF or fitz?

### ISSUE THREAD

**Issue by betterthanever2** [Mirascope/mirascope#477]
### Question

Hi.
In the cookbook about PDF extraction https://docs.mirascope.io/latest/cookbook/extract_from_pdf/, `PyMuPDF` is claimed to be used in the text, but all the examples feature package named `fitz`. 

On top of being confused with this discrepancy, I tried looking up `fitz`, and found only a lib about neuroimaging. 
What is up here?

**Comment by willbakst** [comment]
Ah I see the confusion.

`fitz` is the legacy name for that package and is acting as an alias. We should update this to `import pymupdf` so there isn't any confusion here.

I will make sure this gets fixed in our upcoming docs updates. Thanks for pointing this out!

**Comment by betterthanever2** [comment]
FYI, they have this page on AI integration: https://pymupdf.readthedocs.io/en/latest/rag.html

**Comment by sahibpreetsingh12** [comment]
Hi Also wanted to ask 
if I can add support for Llamaparse API which can also act as a Alternative to any python package.
@willbakst 
If it's ok I can add that functionality

**Comment by willbakst** [comment]
For this particularly cookbook, let's keep it as-is.

However, if you're interested in implemented a more RAG + PDF cookbook recipe and want to use Llama Parse to do that, you're more than welcome to!

Please also submit a separate Feature Request as a GitHub issue outlining what you'll be adding so that we can properly track it there (rather than in this issue).

**Comment by betterthanever2** [comment]
Ok, thank you @willbakst 
Closing this since there is nothing else to add.
