### ISSUE TITLE
✨ MultiAgent & SubAgents support

### ISSUE THREAD

**Issue by jd-solanki** [Mirascope/mirascope#625]
### Description

Hi 👋🏻 

I love the mirascope and its simplicity ❤️ 

I choose it over langchain and other frameworks and now it also has suport for structured outputs I also replaced it from [instructor](https://github.com/instructor-ai/instructor).

---

I'm building highly dynamically API where I receive everything as request body like model name, model provider, prompt, tools etc hopefully everything is possible with mirascope. However, I'm stuck at multiple agent system like AutoGen.

I want to know how to implement multi agent system & sub agent system. This is related to [agency swarm](https://github.com/VRSEN/agency-swarm), agent orchestration, task delegation, etc. I seen the docs on agents but it's limited to single agent only.

Thanks 😇

**Comment by willbakst** [comment]
I'm so glad you're liking Mirascope!

Agents are top of mind for us right now, and we're actively working on additional features/functionality around how to build agents (which is why the Learn section does not yet cover the more complex cases, but I promise docs and examples are coming soon!)

In the meantime, one method of writing multi/sub-agent architectures is to use agents as tools. You can see an example of this in our [Blog Writing Agent](https://mirascope.com/docs/tutorials/agents/blog_writing_agent/) tutorial. Let me know if you have any comments or questions!

Of course, this example gives the agent executor and agents a lot of control. The features we're aiming to build will hopefully make it easier to build multi/sub-agent flows where you have more fine-grained control over the flow without as much boilerplate

**Comment by willbakst** [comment]
After a lot of thinking, I've come to the following conclusion:

We should close this issue in favor of individual issues outlining specific examples you'd like to see.

Here's my reasoning:
1. Mirascope is supposed to be a lightweight toolkit for interacting with LLM APIs. Mirascope sits at the single-layer abstraction level so that it can remain simple and clean, and I intend to keep it this way.
2. This means that things like agents (which I consider higher order abstractions) don't really belong as "features" of Mirascope. You can use Mirascope to build agents the same way you could use the raw OpenAI SDK to build agents. Rather than new "features" or additional "support" Mirascope should have more extensive examples of how to build such agents using Mirascope as-is.
3. We should outline specific architectures / examples and work to implement those as Tutorials so that users can see how to build them with Mirascope. To me, this is what "multiagent and subagent support" really looks like in Mirascope since Mirascope already technically has support for this.

If you already have some ideas / examples around specific architectures or agent designs for which you'd like to see tutorials, please create a GitHub Issue for each one! 🙏  This way we can discuss and track the work individually for each issue. As mentioned at the beginning of this comment, I will be closing this issue in favor of these new individual example issues.

Some additional comments:
- I want to build more features around agents -- just not as part of Mirascope.
- Since Mirascope is only a single-layer abstraction, and agent features are higher order, I envision building any new agent features as part of a separate library (most likely using Mirascope to build it).
- My current intention is to build more agent features in [`Lilypad`](https://github.com/Mirascope/lilypad) instead, which I believe is a better place for such features given that it's a framework (vs. Mirascope which is not a framework).
