### ISSUE TITLE
Do we have a best pratice and elegant way to handle IndexError when accessing response choices in Mirascope OpenAI integration

### ISSUE THREAD

**Issue by minhquan23102000** [Mirascope/mirascope#650]
### Question

**Screenshots:** :
![image](https://github.com/user-attachments/assets/ac5c900c-8cec-401f-9c59-d304535e55f3)

**Expected behavior:** The code should retrieve the first choice from the OpenAI response without errors.

**Actual behavior:** Occasionally, an `IndexError` occurs when trying to access `self.response.choices[0]`, indicating that the `choices` list is empty.

**Proposed solution:** How we can handle this error gracefully?, for example:

```python
if self.response.choices:
    message_param = self.response.choices[0].message.model_dump()
else:
    # Handle the empty choices case, possibly logging an error or returning a default value 
    message_param = None  # or some appropriate default

   log detailed on why the messages list  is empty (Block reason, rate limit, etc)


```

Or user should catch and handle in some way.

**Additional notes:** This issue seems to arise intermittently, possibly due to network issues or message block  with the provider api. Implementing the above check could improve the robustness of the integration.

**Comment by willbakst** [comment]
Yeah, I worry about adding anything internally here since calling `response.choices[0]` would fail if you used the official OpenAI SDK, so it seems like something worth catching on the user's end rather than internally (so that the user knows there was an issue and can handle it rather than having a silent failure).

I think your approach is correct.
