### ISSUE TITLE
`FileSystemToolKit` failing with Gemini example from docs + dependencies are not clear

### ISSUE THREAD

**Issue by willbakst** [Mirascope/mirascope#724]
### Description

> originally mentioned in the slack community by Musa
>
> Hey, I am attempting to run an example script from the mirascope documentation trying out the builtin FileSystemToolKit however, I am receiving this error coming from mirascope. As for context, I installed "mirascope[gemini]" and that was not enough... Apparently to use the toolkit, some more dependencies like docker is required but not documented anywhere I have seen so far. Nevertheless, I installed everything it requires and the is the current issue:
> 
> Code from docs:
> 
> ```python
> from pathlib import Path
> 
> from mirascope.core import BaseDynamicConfig, Messages, gemini
> from mirascope.tools import FileSystemToolKit
> 
> 
> @gemini.call("gemini-1.5-flash")
> def write_blog_post(topic: str, output_file: Path) -> BaseDynamicConfig:
>     toolkit = FileSystemToolKit(base_directory=output_file.parent)
>     return {
>         "messages": [
>             Messages.User(
>                 content=f"Write a blog post about '{topic}' as a '{output_file.name}'."
>             )
>         ],
>         "tools": toolkit.create_tools(),
>     }
> 
> 
> response = write_blog_post("machine learning", Path("introduction.html"))
> if tool := response.tool:
>     result = tool.call()
>     print(result)
> ```
> 
> Error:
> 
> ```plaintext
> Traceback (most recent call last):
>   File "/home/moses/Developer/test/main.py", line 21, in <module>
>     response = write_blog_post("machine learning", Path("introduction.html"))
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/moses/Developer/test/.venv/lib/python3.11/site-packages/mirascope/core/base/_create.py", line 212, in inner
>     create, prompt_template, messages, tool_types, call_kwargs = setup_call(  # pyright: ignore [reportCallIssue]
>                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/moses/Developer/test/.venv/lib/python3.11/site-packages/mirascope/core/gemini/_utils/_setup_call.py", line 97, in setup_call
>     prompt_template, messages, tool_types, base_call_kwargs = _utils.setup_call(
>                                                               ^^^^^^^^^^^^^^^^^^
>   File "/home/moses/Developer/test/.venv/lib/python3.11/site-packages/mirascope/core/base/_utils/_setup_call.py", line 77, in setup_call
>     call_kwargs["tools"] = [tool_type.tool_schema() for tool_type in tool_types]
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/moses/Developer/test/.venv/lib/python3.11/site-packages/mirascope/core/base/_utils/_setup_call.py", line 77, in <listcomp>
>     call_kwargs["tools"] = [tool_type.tool_schema() for tool_type in tool_types]
>                             ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/moses/Developer/test/.venv/lib/python3.11/site-packages/mirascope/core/gemini/tool.py", line 70, in tool_schema
>     if model_schema["required"]:
>        ~~~~~~~~~~~~^^^^^^^^^^^^
> KeyError: 'required'
> ```

On top of the bug, we also need to update the documentation to make it clear what dependencies are needed for each pre-made tool. Perhaps adding a column to the table is sufficient?

**Comment by MusaKhan16** [comment]
I decided to look into the codebase and as hinted by the error, the problem is apparent in the implementation of `GeminiTool.tool_schema`.

During the construction of the tool's schema for the Gemini API, there is a redundant condition that checks if there are "required" attributes on the tool's model schema. Based on that condition it Is either set or ignored on the new schema.

Current implementation:

https://github.com/Mirascope/mirascope/blob/68be19f4599bc084fe6f2aeea6701ab290e9cd7b/mirascope/core/gemini/tool.py#L66C8-L72C31

However, these are already added to the "parameters" from the condition above it, where the "parameters" field is directly set to the tools schema.

https://github.com/Mirascope/mirascope/blob/68be19f4599bc084fe6f2aeea6701ab290e9cd7b/mirascope/core/gemini/tool.py#L67-L69

The error specifically occurs when dealing with the `FileSystemToolKit.ListDirectory` tool and will continue to occur for tools alike due to the lack of "required" parameters. This is because of the visible defaults.

https://github.com/Mirascope/mirascope/blob/68be19f4599bc084fe6f2aeea6701ab290e9cd7b/mirascope/tools/system/_file_system.py#L142C5-L149C68

The solution would be to remove the condition.

**Comment by willbakst** [comment]
We realized that we were not properly suppressing imports for `mirascope.tools`, so even though `FileSystemToolKit` does not require docker, it appeared that way because the `DockerOperationToolKit` does require it and was being imported as part of the module. `v1.11.2` fixed this and also properly lists all of the required dependencies in the docs for each pre-made tool and toolkit.
